### ISSUE TITLE
Add emoji in sub-heading or in the text of the README file

### ISSUE THREAD

**Issue by Pradnyana28** [Pradnyana28/dafis-nodejs-boilerplate#4]
HAPPY HACKTOBERFEST!!!

Please follow the step below before start a new Pull Request:
1. Give a star to this repo
2. Fork this repo
3. Create PR
4. Code review
5. Merging

Happy coding!

**Comment by Palak-137** [comment]
Can I work on this issue?

**Comment by yashasvimisra2798** [comment]
I would like to work on this issue as a part of hacktoberfest.

**Comment by Pradnyana28** [comment]
> Can I work on this issue?

Hi @Palak-137 , of course, I will assign this issue to you.

**Comment by Palak-137** [comment]
I have added the emojis at the required places. Review the pull request.
